### ISSUE TITLE
Media with this code does not exist

### ISSUE THREAD

**Issue by MaximilianYeung** [postaddictme/instagram-php-scraper#1016]
**results has no data**

![image](https://user-images.githubusercontent.com/22850875/149111644-08ceea00-ccba-4068-aa81-8dd0ca919ef6.png)

InstagramScraper\Exception\InstagramException Object
(
    [message:protected] => Media with this code does not exist
    [string:Exception:private] =>
    [code:protected] => 500
    [file:protected] => /Users/max/php/instagram-php-scraper/src/InstagramScraper/Instagram.php
    [line:protected] => 823
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /Users/max/php/instagram-php-scraper/examples/getMediaByUrl.php
                    [line] => 16
                    [function] => getMediaByUrl
                    [class] => InstagramScraper\Instagram
                    [type] => ->
                    [args] => Array
                        (
                            [0] => https://www.instagram.com/p/CX3OQ9gIXLI/
                        )

                )

        )

    [previous:Exception:private] =>
)

**Comment by thristov78** [comment]
![Screenshot 2022-01-12 at 17 13 25](https://user-images.githubusercontent.com/18478372/149169073-cf4088fb-ee7d-4c02-b92d-596c46ec3a59.png)


Same here. I debugged the script a little bit and found out that the request for example https://www.instagram.com/p/CYnlJraMNzC/?__a=1 returns object with property "items" instead of "graphql", and the script throws exception.

The same in Postman using the header data generated from the script. Instagram returned the same object.

What can we do in this case?

**Comment by MaximilianYeung** [comment]
> 

did you solve this problem?

**Comment by thristov78** [comment]
Unfortunately not yet.

**Comment by MaximilianYeung** [comment]
> Unfortunately not yet.

tell me when you solved :)
