### ISSUE TITLE
Something went wrong. Please report issue.

### ISSUE THREAD

**Issue by NetForBit** [postaddictme/instagram-php-scraper#106]
Извиняюсь, но спрошу по-русски. Эта ошибка конкретно означает перегрузку? Или что конкретно?
На локалке работает при любой нагрузке без похожих ошибок, а уже в боевых условиях при нагрузке показывает подобное:

[Thu May 04 10:22:01 2017] [error] [client 91.90.192.164] PHP Fatal error:  Uncaught exception 'InstagramScraper\\Exception\\InstagramAuthException' with message 'Something went wrong. Please report issue.' in /var/www/netforbit/data/www/домен/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:535\nStack trace:\n#0 /var/www/netforbit/data/www/домен/core/instagram.php(5): InstagramScraper\\Instagram->login()\n#1 /var/www/netforbit/data/www/домен/cron/media.php(5): include_once('/var/www/netfor...')\n#2 {main}\n  thrown in /var/www/netforbit/data/www/домен/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 535

**Comment by raiym** [comment]
Похоже, что инстаграм забанил на время

Возможно, что слишком много запросов делаете. попробуйте ожидание поставить
между запросами

**Comment by NetForBit** [comment]
Забанил по IP? Ибо под этим же аккаунтом на локалке все прекрасно работает, именно в то время, когда на vps все колом стоит )

**Comment by raiym** [comment]
Ну если вы ту же сессию используете на сервере, что и на локальном компе,
то скорее всего не прокатит
Надо по новой авторизоваться.

Врядли по ip если не куча запросов. Скорее просто аккаунт, что сессия
подозрительно быстро путешествует


On May 4, 2017 11:32, "Ren" <notifications@github.com> wrote:

Забанил по IP? Ибо под этим же аккаунтом на локалке все прекрасно работает,
именно в то время, когда на vps все колом стоит )

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/postaddictme/instagram-php-scraper/issues/106#issuecomment-299125891>,
or mute the thread

**Comment by NetForBit** [comment]
Спасибо за ответы, нужно думать в сторону мультисессионности.

**Comment by raiym** [comment]
Попробуйте вот что. Когда пушите код на сервер не грузите кеш сессии с локального компа, а логинтесь прям на сервере

**Comment by NetForBit** [comment]
Поменял папку сессии, подчистил все, то же самое выдает ( 
думаю просто с моей стороны неадекватно грузить столь большие объемы информации с одного аккаунта. Только странно, почему на локалке всеже работает при том же объеме нагрузки...
Думаю проще приписать подгрузку 5 - 10 дополнительных аккаунтов и распределить нагрузку между ними.

**Comment by raiym** [comment]
Понял

**Comment by NetForBit** [comment]
И действительно, раскидал нагрузку по разным аккаунтам, помогло. полчаса без ошибок.
