### ISSUE TITLE
getAccountByid() returns the wrong user account

### ISSUE THREAD

**Issue by TorbenL** [postaddictme/instagram-php-scraper#220]
![image](https://user-images.githubusercontent.com/526954/33020357-52734e36-cdfe-11e7-93e4-bef71ef8c5b0.png)

Hi,
first I want to thank you for offering this great package! It is really helpful!

I just have one little issue while using `$instagram->getAccountById()`. The method returns always the same user, no matter which ID I hand over.

**Comment by Parviz-Turk** [comment]
it's because this url doesn't work anymore : 
const FOLLOW_URL = 'https://www.instagram.com/web/friendships/{{accountId}}/follow/';

and always return user page by username : follow

file : src/InstagramScraper/Endpoints.php

**Comment by Parviz-Turk** [comment]
i found the solution, you must get user info by Credentials otherwise the above FOLLOW_URL will redirect you to this url > https://www.instagram.com/accounts/login/?next=/web/friendships/{user-id}/follow/

example code : 

$instagram = \InstagramScraper\Instagram::withCredentials('username', 'password', '/path/to/cache/folder');
$instagram->login();
$account = $instagram->getAccountById('3');

**Comment by TorbenL** [comment]
Thanks @Parviz-Turk, I'll try it out!
