### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by zaivst** [postaddictme/instagram-php-scraper#446]
When I use $instagram->login(); I`m got an extension "Something went wrong. Please report issue." without any additional information. Im try to login both with and without proxy but no result.

**Comment by jmarchalonis** [comment]
```
$challenge_url = 'https://www.instagram.com' . $response->body->checkpoint_url;
$response = Request::post( $challenge_url , $headers, [ 'choice' => true ] );
```
I was playing around with this issue. If you interrupt the response on line 1287 of Instagram.php, you will see that the response body contains a challenge. To get the url, you look at $response->body->checkpoint_url. The choice is either true or false; "This was me | This wasn't me". 

If you send a post confirming your response, you get to the next page which will send a code to your email. The problem is getting beyond this part. You have to physically get the code yourself and submit it. I have seen another scrapper do the process, then show a form and ask for the code. After you manually submit that form, it saves the session like normal. While this could be a solution, it doesn't work for automated systems with cron-jobs. It seems that instagram doesn't want anybody having access to their platform via web.

**Comment by hamlet96** [comment]
+1

**Comment by hamlet96** [comment]
@raiym please tell us how to use CLI method, and don't use login function, because I got same error

**Comment by fsjdg** [comment]
I got same error. What i realized is that instagram now is asking for 6 code number ( randomly ), even if two factor authentication is disabled. So i went to instagram.php file, line 1288 and removed from the if statement the `$support_two_step_verification` variable. You will skip this error but still you need to figure it out how to get the code and finish the login process, which doesn't seem too hard.

**Comment by lexotrion** [comment]
I made a way to automate two step verification with email as example in https://github.com/postaddictme/instagram-php-scraper/pull/457

**Comment by jmarchalonis** [comment]
> I made a way to automate two step verification with email as example in #457

I see what you did there. Clever. I am assuming it only works with IMAP mail services... which is most email providers today anyway.

**Comment by lexotrion** [comment]
Login with email via IMAP is just an example of two step verification interface implementation. So you can implement any other method...

**Comment by nicmare** [comment]
> I made a way to automate two step verification with email as example in #457

does not work entirely. there is no exception class. whole class named different. unknown constants... do you linked to the correct class?
