### ISSUE TITLE
Account with this username was not found [getAccount not working]

### ISSUE THREAD

**Issue by 27RU57** [postaddictme/instagram-php-scraper#555]
As today getAccount endpoint is problaby not working. Anyone else have issues?

**Comment by 27RU57** [comment]
And can't we use implementation of https://www.instagram.com/{{username}}/?__a=1?

**Comment by zaivst** [comment]
Works correct if you will try it in browser. But in lot of cases ig block it when using in the script....

**Comment by 27RU57** [comment]
I don't understand how it's possible, how they can even block anything if you're using useragent. It should react like browser right?

**Comment by zaivst** [comment]
I dont know too, but seems that they can....

**Comment by fsjdg** [comment]
it can be related to your IP address. Are you using proxies?  Try using dedicated proxies to avoid this issue

**Comment by gianlucainnocente** [comment]
Same problem here.. No proxies. But only 404 error

**Comment by beshoo** [comment]
It is ip related problem. it is very hard nowadays to solve this problem!
OMG, Instagram becomes a nasty place to work with

**Comment by retrowaver** [comment]
Yeah, it's IP thing for sure. But for me the problem is, it shouldn't throw `InstagramNotFoundException` in such case, but rather `InstagramException`.

Are we sure there is a case where [this line](https://github.com/postaddictme/instagram-php-scraper/blob/924cc5e586bfc0895f331409312f4cdc257b770e/src/InstagramScraper/Instagram.php#L353) is called and the account actually doesn't exist? Shouldn't response status code check be enough?

**Comment by fsjdg** [comment]
oh, i get what you mean! I'm actually having the same problem! We need to make some tests and propose some changes!!
