### ISSUE TITLE
Error when 'Location' prop is NULL

### ISSUE THREAD

**Issue by iyhunko** [postaddictme/instagram-php-scraper#590]
src/InstagramScraper/Model/Media.php    line 575

Since location can be NULL, we get errors for accounts where it's null.

Solution:
```
case 'location':
                $this->locationId = $arr[$prop]['id'];
                $this->locationName = $arr[$prop]['name'];
                $this->locationSlug = $arr[$prop]['slug'];
```
=>
```
case 'location':
                $this->locationId = $arr[$prop]['id'] ?? null;
                $this->locationName = $arr[$prop]['name'] ?? null;
                $this->locationSlug = $arr[$prop]['slug'] ?? null;
```

**Comment by jj-dev** [comment]
@raiym any chance you can fix with @iyhunko solution.

The merge turning it into just a ternary is the wrong solution unless you also wrap the condition in an isset(), otherwise it'll still complain with "Trying to access array offset on value of type null" trying to access the id, name and slug.

The null coalescing operator is needed so its this:

$arr[$prop]['id'] ?? null;

or the longer way:

isset($arr[$prop]['id']) ? $arr[$prop]['id'] : null;

**Comment by jj-dev** [comment]
So just spotted https://github.com/postaddictme/instagram-php-scraper/pull/610 waiting to be pulled...
