### ISSUE TITLE
please make it clear how to log-in 

### ISSUE THREAD

**Issue by soheilara96** [postaddictme/instagram-php-scraper#703]
I cant log in to instagram becuase the cache mechanism is not clear how to use it
$instagram = \InstagramScraper\Instagram::withCredentials('soheilaraei', 'AAssdd11', 'cache?');

**Comment by lucasff** [comment]
you use any instance of a PHP PSR-16 compatible interface.

**Comment by yinanchuan** [comment]
composer require phpfastcache/phpfastcache

`$cacheOptions = array(
            'path' => '/temp/'
        );
        $instanceCache = new \Phpfastcache\Helper\Psr16Adapter('Files', $cacheOptions);
        $instagram = Instagram::withCredentials($username, $password, $instanceCache);`

**Comment by jenswittmann** [comment]
I think you need also [PhpFastCache](https://github.com/PHPSocialNetwork/phpfastcache) via composer.

`use Phpfastcache\Helper\Psr16Adapter;`
`$instagram = \InstagramScraper\Instagram::withCredentials('username', 'password', new Psr16Adapter('Files'));`

Then it should work on local, on production it can be blocked because the instagram may update. Another way is [this snippet](https://github.com/abubakar-iqbal/Instagram-scrapper) or a service like [nocodeapi.com](https://nocodeapi.com/).
