### ISSUE TITLE
Error: Something went wrong

### ISSUE THREAD

**Issue by filippodicostanzo** [postaddictme/instagram-php-scraper#762]
`Fatal error: Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong. Please report issue. in Y:\php.localidautore.it\insta-new\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php:1681`

Anyone have a solution for this problem?

```
use InstagramScraper\Instagram;
use Phpfastcache\Helper\Psr16Adapter;

Unirest\Request::verifyPeer(false);

$instagram = \InstagramScraper\Instagram::withCredentials(
    $username,
    $password,
    new Phpfastcache\Helper\Psr16Adapter('Files'));

$instagram->login();
$instagram->saveSession();

try {
    $account = $instagram->getAccountById(3);
    echo $account->getUsername();

} catch (InstagramException $ex) {
    echo $ex->getMessage();
}
```

**Comment by MagnusTv** [comment]
Same problem :)

**Comment by l-uke** [comment]
what is save session for ?

**Comment by MagnusTv** [comment]
> what is save session for

With saveSession, I think, you can login instantly with `$instagram->login(true);` but im not sure at all.

**Comment by Tutt-J** [comment]
Same error

**Comment by cacing69** [comment]
![image](https://user-images.githubusercontent.com/36250619/92944664-7d17f480-f47e-11ea-8f79-05f6a48b9c45.png)
same problem here

**Comment by cuchac** [comment]
I got it working only after turning on 2 factor authentication using SMS.
To make it work in cron/daemon, just launch manually from command line, insert received SMS code on cli, save session cookies and close. Then cron/daemon works witout login for several months.

**Comment by iankaufmann** [comment]
> I got it working only after turning on 2 factor authentication using SMS.
> To make it work in cron/daemon, just launch manually from command line, insert received SMS code on cli, save session cookies and close. Then cron/daemon works witout login for several months.

Is there any documentation showing how to accomplish this via cli?

**Comment by iankaufmann** [comment]
I had zero luck with the CLI method.  Consistently ran into 400 bad request and the library just doesn't seem to want to handle the current SMS 2FA.

Here is what worked for me in case anybody sees this:

I logged in on my computer from my office IP address, which I have also set the library up to proxy through.

- Clear out your Phpfastcache cache folder

- Open chrome and look at the Application tab and browse the cookies for instagram.com

- Create a php file with the following and run it once manually.  You need to do this in the browser, not cli, because of how Phpfastcache stores the cache files.  You need this to come from the same method your regular scraper runs.

```
<?php 

$cacheKey = md5($instagram_username);

// Fill-in cookies from browser here
$cookies = [
    "urlgen" => '',
    "rur" => '', 
    "csrftoken" => '',
    "mid" => '',
    "sessionid" => '',
    "ds_user_id" => '',
    "ig_did" => ''
];

\Phpfastcache\CacheManager::setDefaultConfig(new \Phpfastcache\Config\ConfigurationOption([
    'path' => $path_to_cache,
    'defaultTtl' => (60 * 60 * 24 * 365) # One Year
])); 

$instanceCache = \Phpfastcache\CacheManager::getInstance('Files');

$cachedString = $instanceCache->getItem($cacheKey);

$instanceCache->save($cachedString);
```

- Double check your cache folder to make sure it wrote properly

- In your scraper code, make sure to set $instagram->setUserAgent() to match your computer's useragent


Your scraper should now basically look no different than your computer to Instagram.  Same IP, same cookies, same useragent.


```
<?php 

\Phpfastcache\CacheManager::setDefaultConfig(new \Phpfastcache\Config\ConfigurationOption([
    'path' => $path_to_cache,
    'defaultTtl' => (60 * 60 * 24 * 365) # One Year
]));

Unirest\Request::verifyPeer(false);

$instagram = \InstagramScraper\Instagram::withCredentials($instagram_username, $instagram_password, new \Phpfastcache\Helper\Psr16Adapter('Files'));

\InstagramScraper\Instagram::setProxy($proxy_config);

$instagram->setUserAgent($useragent);  // Set useragent to match your computer's browser
$instagram->login();
$instagram->saveSession();

$medias = $instagram->getMedias($feed_username, $feed_limit);

var_dump($medias);
```

Hopefully this holds for a while...

**Comment by ankitsinghmyself** [comment]
same issue
