### ISSUE TITLE
Please report issue

### ISSUE THREAD

**Issue by APTEMOH** [postaddictme/instagram-php-scraper#793]
Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is 429. Body: message => rate limited; status => fail; Something went wrong. Please report issue. in /vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:786

**Comment by PrasadBroo** [comment]
im also facing same problem anyone have solution to avoid being rate limited?

**Comment by lon9man** [comment]
+1

**Comment by jeybin** [comment]
@APTEMOH 

I think the exception throws because of the continues login into the same instagram profile. Try using some other account
If it works try to avoid continuous login by, saving the instagram session and call the function  as you desired using the saved session .

refer: [#789](https://github.com/postaddictme/instagram-php-scraper/issues/789)
