### ISSUE TITLE
Uncaught InstagramScraper\Exception\InstagramException: Response code is 302. Body: Something went wrong

### ISSUE THREAD

**Issue by alabamaster** [postaddictme/instagram-php-scraper#811]
Fatal error: Uncaught InstagramScraper\Exception\InstagramException: Response code is 302. Body: Something went wrong. Please report issue. in /home/web/.../vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:426 Stack trace: #0 /home/web/.../tests/index.php(10): InstagramScraper\Instagram->getAccount('alabamaster1337') #1 {main} thrown in /home/web/.../vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 426

**this from example getAccountByUsername.php**

**Comment by Theder** [comment]
It seems, that you ip is not allowded to check instagram account without authorization. You can authorize to scrape accounts or change ip.

**Comment by restyler** [comment]
Just changing ip to another one in the datacenter may fail, since Instagram blocked datacenter ip ranges a long time ago. Even residential proxies are actively banned by Instagram every day. Take a look at https://github.com/restyler/instagram-php-scraper which is the proxified version of this scraper, it uses smart proxy network.
