### ISSUE TITLE
getAccount 302 error

### ISSUE THREAD

**Issue by joe7pt** [postaddictme/instagram-php-scraper#844]
Getting error when trying to get this account info

$instagram = new \InstagramScraper\Instagram(new \GuzzleHttp\Client());

// For getting information about account you don't need to auth:

$account = $instagram->getAccount('lisboacool');

**Comment by restyler** [comment]
302 redirect (to login page) typically happens if you try to connect to Instagram via datacenter ip range. Instagram only allows residential ip addresses so your best bet is to use 1) your home network, 2) clean residential proxies or 3) this repo fork https://github.com/restyler/instagram-php-scraper

**Comment by APTEMOH** [comment]
> 302 редирект (на страницу входа) обычно происходит, если вы пытаетесь подключиться к Instagram через диапазон IP-адресов центра обработки данных. Instagram разрешает только частные IP-адреса, поэтому лучше всего использовать 1) вашу домашнюю сеть, 2) чистые жилые прокси или 3) эту вилку репо https://github.com/restyler/instagram-php-scraper

{"message":"You are not subscribed to this API."}
