### ISSUE TITLE
json_encode Not Work !

### ISSUE THREAD

**Issue by mohammadrezajiji** [postaddictme/instagram-php-scraper#882]
$medias = $instagram->getMedias('username' , 10);
echo json_encode($medias);

 i use this for json encode result but don't json encode maybe for protected array how can fix this ?
[array  result photo](https://i.stack.imgur.com/OdY5Y.jpg)
Thank

**Comment by suraj853** [comment]
try json_encode($medias,true);

**Comment by PrasadBroo** [comment]
try this `json_encode(json_decode($medias));`

**Comment by toppersdesk** [comment]
> try this `json_encode(json_decode($medias));`

This didn't help me at all. It gave `null` output.



> $medias = $instagram->getMedias('username' , 10);
> echo json_encode($medias);
> 
> i use this for json encode result but don't json encode maybe for protected array how can fix this ?
> [array result photo](https://i.stack.imgur.com/OdY5Y.jpg)
> Thank

The main reason of why json_encode didn't work is because the returned `$medias` containes non utf-8 encoded strings [(as seen in this issue)](https://stackoverflow.com/questions/36958670/php-print-r-works-but-json-encode-returns-empty).
Probably there should be an option added to get either the json string or the decoded array in `$medias`.

**Comment by toppersdesk** [comment]
This [solution](https://stackoverflow.com/questions/27350473/how-to-convert-this-php-array-of-objects-to-json) may help you.
